server:
  port: 8767

spring:
  application:
    name: mt-user-feign
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8080/eureka
    instance:
      status-page-url: http://localhost:${server.port}/swagger-ui.html
      #把服务机的ip注册到eureka上，false表示把服务机机器名注册到eureka上
      prefer-ip-address: true