spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.31.234:3306/test?useUnicode=true&characterEncoding=utf-8
    username: pxsjtest
    password: pxsj_123
mybatis:
  type-aliases-package: com.spring.service.user
  config-locations:
    classpath: com.spring.config.mybatis-config.xml
  mapper-locations:
    classpath: com.spring.mapper/*.xml
  