server:
    port: 8765
    session-timeout: 60
spring:
    application:
        name: zuul-server
    cloud:
        loadbalancer:
            retry:
                enabled: true   #启动负载均衡的重试机制，默认false

#向eureka服务注册信息时，使用ip地址，默认使用hostname
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8080/eureka
        healthcheck:
            enabled: true    #开启健康检查(需要spring-boot-starter-actuator依赖)
    instance:
        preferIpAddress: true
        instance-id: ${spring.cloud.client.ipAddress}:${server.port}
        lease-expiration-duration-in-seconds: 30   #租期到期时间，默认90秒
        lease-renewal-interval-in-seconds: 10      #租赁更新时间间隔，默认30，即30秒发送一次心跳
zuul:
    routes:
        api-a:
            path: /api-user/**
            service-id: user-service
        api-b:
            path: /api-order/**
            service_id: order-service	